-- playlists-faciles-par-type.sql — 13 septembre 2026
--
-- Thomas : « je veux juste un niveau par type et des musiques faciles et
-- connues avec les titres des films comme réponse en français et en anglais ».
--
-- Appliqué directement en base le 13/09/2026. Conservé ici pour mémoire.
--
-- Résultat : exactement trois playlists « devine l'œuvre » visibles, toutes
-- EASY, toutes 100 % Apple Music, toutes avec alias FR + EN :
--   1. Musiques de film — Faciles        70 titres  (existait déjà)
--   2. Génériques de séries — Faciles    40 titres  (créée ici)
--   3. Dessins animés — Faciles          47 titres  (créée ici)
--
-- Les séries viennent de official-pl-series-tv, après passage de
-- enrichAppleMusicIds.ts qui a fait monter la couverture Apple de 19 à 52/85.
-- Les dessins animés viennent de official-pl-generiques-disney (103/116 après
-- enrichissement), un à deux titres par film pour éviter les répétitions.
--
-- Le catalogue éditorial Apple n'a servi qu'aux films : sa seule playlist de
-- séries, « Entendu à la télé », contient des chansons entendues dans des
-- séries et non des génériques — inutilisable pour deviner la série.
--
-- Corrections de données faites au passage :
--   • « Eye of the Tiger » était rattaché à Rocky IV. C'est Rocky III (1982) —
--     Rocky IV, c'est « Burning Heart ». Corrigé sur les 3 playlists Apple.
--   • « Rocky » accepté seul pour Rocky et Rocky III.
--   • « Star Wars » accepté seul, plus « La Guerre des étoiles ».
--   • « Les Blues Brothers » ajouté en titre français.
--
-- Vérification : les 87 identifiants Apple des deux nouvelles playlists
-- résolvent tous dans le store FR (87/87).

-- ─────────────────────────────────────────────────────────────────────────────
-- Complément du 13/09 — les sagas répondues par leur nom court
--
-- Thomas : « seigneur des anneaux -> lord of the rings ».
--
-- Un joueur répond « Le Seigneur des Anneaux », pas « Le Seigneur des Anneaux :
-- La Communauté de l'Anneau ». Les alias ne contenaient que l'intitulé complet,
-- donc la bonne réponse était refusée. Corrigé pour :
--   • Le Seigneur des Anneaux (Communauté de l'Anneau + Retour du Roi)
--   • Pirates des Caraïbes
--   • Top Gun: Maverick  → « top gun » accepté
--   • La Reine des Neiges 2 → « la reine des neiges » accepté
-- (Star Wars et Rocky III avaient déjà été traités.)
--
-- CORRIGÉ AUSSI À LA SOURCE, pour que ça ne revienne pas : le générateur
-- d'alias (src/lib/aliasGeneration.ts) réclame désormais deux champs de plus,
-- franchise_fr et franchise_en, à remplir uniquement quand l'œuvre porte un
-- sous-titre ou un numéro. backfillWorkTranslations.ts les verse dans
-- work_aliases. Les œuvres autonomes (Titanic, Le Roi Lion) renvoient null.
